### ISSUE TITLE
bug fix

### ISSUE THREAD

**Issue by dmolony** [AlanKrueger/freehost3270#1]
I have a bug fix, but can't find a way to communicate it.

**Comment by AlanKrueger** [comment]
You should probably send it to the [FreeHost3270 project](https://sourceforge.net/projects/freehost3270/).  I forked this from the SourceForge project because it looked like it was dead, but there has been some sort of activity over there recently.  Also, I'm no longer working with the code and won't be able to contribute to forward motion on this project.

**Comment by dmolony** [comment]
I've emailed both the original authors, neither is interested in working on it. I guess I'll just keep the new version for myself :)

**Comment by dmolony** [comment]
Did you ever receive the updated source from this guy?

I've replied to him also, but so far no response. If you have the updated code I would love to have a copy too.
